"""add resume ingestion pipeline

Revision ID: 9e5315975690
Revises: 3c61195e165e
Create Date: 2026-07-29 00:56:12.565256
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9e5315975690"
down_revision: str | None = "3c61195e165e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume_imports",
        sa.Column("profile_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("parsing_status", sa.String(length=32), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["career_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resume_imports_checksum"), "resume_imports", ["checksum"], unique=True)
    op.create_index(
        op.f("ix_resume_imports_parsing_status"),
        "resume_imports",
        ["parsing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_imports_profile_id"),
        "resume_imports",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "parsed_facts",
        sa.Column("import_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("rejected", sa.Boolean(), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_id"], ["resume_imports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsed_facts_entity_type"),
        "parsed_facts",
        ["entity_type"],
        unique=False,
    )
    op.create_index(op.f("ix_parsed_facts_import_id"), "parsed_facts", ["import_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parsed_facts_import_id"), table_name="parsed_facts")
    op.drop_index(op.f("ix_parsed_facts_entity_type"), table_name="parsed_facts")
    op.drop_table("parsed_facts")
    op.drop_index(op.f("ix_resume_imports_profile_id"), table_name="resume_imports")
    op.drop_index(op.f("ix_resume_imports_parsing_status"), table_name="resume_imports")
    op.drop_index(op.f("ix_resume_imports_checksum"), table_name="resume_imports")
    op.drop_table("resume_imports")
    # ### end Alembic commands ###
